### ISSUE TITLE
Losing Complex Embedding real or imaginary part

### ISSUE THREAD

**Issue by 2003pro** [Panda0406/Zero-shot-knowledge-graph-relational-learning#2]
Hi, Pengda. Thanks for sharing the code.
After downloading the given dataset, I found that the Complex embedding matrix in the directory Embed_used misses real or imaginary part. More details are shown below.
ComplEx.npz only has a matrix with the shape (69127, 100).
Both TransE.npz and DistMult.npz have embedding matrix with the shape (65567, 100).
According the implementation details, ComplEx should be (69127, 200).

**Comment by Panda0406** [comment]
Thanks for your attention. It is my mistake that does not upload the original KG embed npz files.  The files in ./NELL/Embed_used are the intermediate results. I have uploaded a new version of origin_data. Please check. One thing that needs to be mentioned that when using Complex embeddings, you should rename "ComplEx_embed_re.npz" (or "ComplEx_embed_im.npz") to "ComplEx_embed.npz".

**Comment by tonygracious** [comment]
@2003pro  Is it possible for you to share the datasets in google drive with me? I'm not able to download the baidu links.

**Comment by 2003pro** [comment]
@Panda0406 Thank you Pengda. @tonygracious Unfortunately, I am also suffering from VPN issue similar with @Panda0406 right now. I am not able to share in google drive right now.
