### ISSUE TITLE
Can you provide google drive links ?

### ISSUE THREAD

**Issue by tonygracious** [Panda0406/Zero-shot-knowledge-graph-relational-learning#3]
I'm unable to download your datasets from baidu. Can you make the links accessible for people outside china?

**Comment by Panda0406** [comment]
Sorry about that. I merely can access Google Drive on campus, but now I am prohibited to go back to campus because of COVID-19. I am trying to come up with a solution like VPN. I will quickly solve it and then inform you. Thanks again for your attention.

**Comment by myh1234567** [comment]
hello 

can you create a direct download link from Google Drive?

Thank you

**Comment by Panda0406** [comment]
Done. I am sorry for that.
