### ISSUE TITLE
Issue about code on Wiki dataset

### ISSUE THREAD

**Issue by genggengcss** [Panda0406/Zero-shot-knowledge-graph-relational-learning#5]
Hi, Pengda. I am very very interested in your work, it's really a good job!
I tried to run your code recently, but I found it can't work well on Wiki-ZS dataset. I guess it may because the selection of extractor pretrain times. You have provided the pretrain times for NELL (16000), but I think 16000 may not be the best choice for Wiki. Could you provide your pretrain times for Wiki?
Sincerely hope for your reply.

**Comment by Panda0406** [comment]
Thanks for your attention. Below is my ZS-Wiki setting. (That should be the setting for my AAAI paper. Now I have graduated from school and work at the company, and GPU devices of the company are not allowed to upload and run my own code. So I do not re-run the code.)

###########
grad_clip: 5.0
noise_dim: 15
dataset: Wiki
D_epoch: 5
test_sample: 20
seed: 0
pretrain_margin: 10.0
G_epoch: 1
weight_decay: 0.0
pretrain_few: 30
REG_W: 0.001
train_times: 6000
no_meta: False
pretrain_batch_size: 128
embed_dim: 50
G_SN: False
pretrain_subepoch: 30
D_SN: False
save_path: models/intial
test: False
REG_Wz: 0.0001
gan_batch_rela: 8
embed_model: DistMult
pretrain_loss_every: 200
loss_every: 200
dropout: 0.5
w_dim: 50
aggregate: max
D_batch_size: 64
pretrain_times: 7000
device: 0
prefix: intial
max_neighbor: 50
lr_G: 0.0001
lr_E: 0.0005
lr_D: 0.0001
fine_tune: False
G_batch_size: 64
###########

**Comment by genggengcss** [comment]
Thanks for your quick reply, it can work well now. Thank you very much!

**Comment by ToneLi** [comment]
HI @genggengcss , can you get the report results from this paper?
